# -*- coding: utf-8 -*-
"""Assignment dt.31.08.2025 Prakash Giri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImKhWUb_Abuh7Kp_rXoarlH6Wd8FF6Mk

# Character Profile
character_profile = {'name': 'Alistair the Brave','level':1,                    'health': 100,'mana': 50,'gold': 50.75,'is_alive': True}
"""

character_profile = {'name': 'Alistair the Brave', 'level': 1, 'health': 100, 'mana': 50, 'gold': 50.75, 'is_alive': True}

print(f"{character_profile['name']} is at level {character_profile['level']}.")

character_profile['health'] = 85

character_profile['health']

character_profile['experience'] = 0

character_profile['experience']

print(character_profile)

inventory = ['sword', 'shield', 'health potion']

inventory.append('mana potion')

inventory.remove('shield')

print("Inventory items:")
for item in inventory: print("-", item)

"""Part 3: Character Stats (Using Tuples)

"""

base_stats = (10, 8, 12)  # (strength, dexterity, intelligence)

print("Tuples are a good choice for base stats because they are immutable and cannot be changed accidentally.")

print(f"Alistair's Intelligence: {base_stats[2]}")

"""In Tuple once created, their elements cannot be changed, added, or removed. We have to delete and redo.Attempting to change an element raises a TypeError."""

# Initialize the set with a few quests
quest_log = {'Defeat the Goblin King', 'Find the Lost Amulet'}

# Add a new quest to the log
quest_log.add('Deliver the Old Scroll')

# Attempt to add a duplicate quest
quest_log.add('Defeat the Goblin King')

print(quest_log)

"""There is no changes. when we tried to add "Defeat the Goblin King". Python ignore the duplication and there were no changes."""

# Remove a completed quest
quest_log.remove('Find the Lost Amulet')

# Print the final quest_log set
print(quest_log)

character_profile = {'name': 'Alistair','class': 'Warrior','level': 5,'race': 'Human'}
inventory = ['Sword', 'Shield', 'Healing Potion']
base_stats = (10, 8, 7)  # strength, agility, intelligence
quest_log = {'Defeat the Goblin King', 'Deliver the Old Scroll'}
character_sheet = {'profile': character_profile,'inventory': inventory,'stats': base_stats,'quests': quest_log}
print(character_sheet)